language: ruby
sudo: false
rvm:
  - 3.1
script:
  - bundle exec jekyll --version
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --allow-hash-href --url-ignore "/^.*scholar.google.*$" --http-status-ignore 429
-env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
# Source
# --
# https://www.jacobtomlinson.co.uk/jekyll/2015/02/18/test-you-jekyll-blog-with-travis-ci/
